/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.employee;

import controller.employee.EmployeeController;
import java.awt.Dimension;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JTextField;
import model.employee.Employee;
import utilities.ComboBoxUtility;

/**
 *
 * @author Mampitiya
 */
public class SearchEmployee extends javax.swing.JInternalFrame {

    private EmployeeController empController;

    /**
     * Creates new form SearchEmployeeForm
     *
     * @param employeeController
     */
    public SearchEmployee(EmployeeController employeeController) {
        initComponents();
        imageLbl.setMaximumSize(new Dimension(128, 128));
        imageLbl.setPreferredSize(new Dimension(128, 128));
        imageLbl.setMinimumSize(new Dimension(128, 128));
        empController = employeeController;
        try {
            ComboBoxUtility.setComboItem(idCmbx, "Select employeeId from employee order by 1");
            JTextField textField = (JTextField) idCmbx.getEditor().getEditorComponent();
            new ComboBoxUtility().setSearchableCombo(idCmbx, textField, "No such employee..");

            ComboBoxUtility.setComboItem(nameCmbx, "Select concat(firstName, ' ', lastName) as name from employee");
            JTextField textField1 = (JTextField) nameCmbx.getEditor().getEditorComponent();
            new ComboBoxUtility().setSearchableCombo(nameCmbx, textField1, "No such employee..");
        } catch (SQLException | ClassNotFoundException ex) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        lblDesignation = new javax.swing.JLabel();
        txtMobile = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        panelProfilePic = new javax.swing.JPanel();
        imageLbl = new javax.swing.JLabel();
        idCmbx = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        accessLvlTxt = new javax.swing.JTextField();
        clearBtn = new javax.swing.JButton();
        designationTxt = new javax.swing.JTextField();
        nameCmbx = new javax.swing.JComboBox();

        setBorder(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search Employee Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        lblID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblID.setText("Employee ID :");

        lblName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblName.setText("Name :");

        lblAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAddress.setText("Address :");

        txtAddress.setEditable(false);
        txtAddress.setColumns(20);
        txtAddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtAddress.setRows(5);
        txtAddress.setWrapStyleWord(true);
        txtAddress.setAutoscrolls(false);
        jScrollPane1.setViewportView(txtAddress);

        lblDesignation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblDesignation.setText("Designation: ");

        txtMobile.setEditable(false);
        txtMobile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Mobile No :");

        panelProfilePic.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Profile Image", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        imageLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/employee_images/business_user.png"))); // NOI18N

        javax.swing.GroupLayout panelProfilePicLayout = new javax.swing.GroupLayout(panelProfilePic);
        panelProfilePic.setLayout(panelProfilePicLayout);
        panelProfilePicLayout.setHorizontalGroup(
            panelProfilePicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfilePicLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelProfilePicLayout.setVerticalGroup(
            panelProfilePicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProfilePicLayout.createSequentialGroup()
                .addComponent(imageLbl)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        idCmbx.setEditable(true);
        idCmbx.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        idCmbx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "     " }));
        idCmbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idCmbxActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Access Level: ");

        accessLvlTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        accessLvlTxt.setEnabled(false);

        clearBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        designationTxt.setEditable(false);
        designationTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        nameCmbx.setEditable(true);
        nameCmbx.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nameCmbx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "    " }));
        nameCmbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameCmbxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName)
                                    .addComponent(lblID))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(idCmbx, 0, 175, Short.MAX_VALUE)
                                    .addComponent(nameCmbx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(accessLvlTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 231, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddress)
                            .addComponent(lblDesignation))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(designationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(panelProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblID)
                                    .addComponent(idCmbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblName)
                                    .addComponent(nameCmbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddress)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDesignation)
                            .addComponent(designationTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(panelProfilePic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accessLvlTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        idCmbx.setSelectedIndex(0);
        txtAddress.setText("");
        nameCmbx.setSelectedIndex(0);
        txtMobile.setText("");
        designationTxt.setText("");
        accessLvlTxt.setText("");
        imageLbl.setIcon(new ImageIcon(getClass().getResource("/resources/employee_images/business_user.png")));
    }//GEN-LAST:event_clearBtnActionPerformed

    private void nameCmbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameCmbxActionPerformed
        String name = "";
        if (nameCmbx.getSelectedItem() != null && nameCmbx.getSelectedIndex() != 0) {
            name = nameCmbx.getSelectedItem().toString();
            try {
                Employee employee = empController.searchEmployeeByName(name);
                txtAddress.setText(employee.getAddress());
                txtMobile.setText(employee.getMobile());
                accessLvlTxt.setText(employee.getAccessLevel() + "");
                designationTxt.setText(employee.getDesignation());
                imageLbl.setIcon(employee.getImage());
                idCmbx.setSelectedItem(employee.getEmployeeID());
            } catch (ClassNotFoundException | SQLException | NullPointerException ex) {
            }
        }
    }//GEN-LAST:event_nameCmbxActionPerformed

    private void idCmbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCmbxActionPerformed
        String id = null;
        if (idCmbx.getSelectedItem() != null) {
            id = idCmbx.getSelectedItem().toString();
            System.out.println(id);
        }
        if (id != null && !id.equals("No such employee..")) {
            try {
                Employee employee = empController.searchEmployeeByID(id);
                if (employee != null) {
                    nameCmbx.setSelectedItem(employee.getFirstName() + " " + employee.getLastName());
                    txtAddress.setText(employee.getAddress());
                    txtMobile.setText(employee.getMobile());
                    accessLvlTxt.setText(employee.getAccessLevel() + "");
                    designationTxt.setText(employee.getDesignation());
                    imageLbl.setIcon(employee.getImage());
                }
            } catch (SQLException | ClassNotFoundException | NullPointerException ex) {
            }
        }
    }//GEN-LAST:event_idCmbxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accessLvlTxt;
    private javax.swing.JButton clearBtn;
    private javax.swing.JTextField designationTxt;
    private javax.swing.JComboBox idCmbx;
    private javax.swing.JLabel imageLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblDesignation;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblName;
    private javax.swing.JComboBox nameCmbx;
    private javax.swing.JPanel panelProfilePic;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtMobile;
    // End of variables declaration//GEN-END:variables
}
