/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import controller.employee.EmployeeController;
import controller.employee.WorkingDetailsController;
import controller.student.AttendanceController;
import controller.student.StudentDetailController;
import java.awt.Dimension;
import java.io.File;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import model.employee.Employee;
import utilities.BarcodeReader;
import view.attendance.AttendanceManagement;
import view.employee.AddEmployee;
import view.employee.DeleteEmployee;
import view.employee.EditEmployee;
import view.employee.SearchEmployee;
import view.employee.ViewWorkingDetail;
import view.exam.Exams;
import view.exam.Marks;
import view.exam.Peformance;
import view.login.LoginWindowInterface;
import view.other.AccountSettings;
import view.other.Help;
import view.payment.AddPayment;
import view.payment.DeletePayment;
import view.student.AddStudent;
import view.student.DeleteStudent;
import view.student.EditStudent;
import view.student.SearchStudent;

/**
 *
 * @author Mampitiya
 */
public class MainGUI extends javax.swing.JFrame {
    
    private static String username;
    private String userID = null;
    Employee employee = null;

    /**
     * Creates new form MainGUI
     */
    public MainGUI(String userID, Employee employee) {
        initComponents();
        userImage.setMaximumSize(new Dimension(136, 130));
        userImage.setPreferredSize(new Dimension(136, 130));
        userImage.setMinimumSize(new Dimension(136, 130));
        
        this.userID = userID;
        this.employee = employee;
        
        if (employee.getImage() != null) {
            userImage.setIcon(employee.getImage());
        } else {
            userImage.setText("Not Available");
        }
        
        usrNme.setText(employee.getFirstName() + employee.getLastName());
        IDNum.setText(employee.getDesignation());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        mainTabPane = new javax.swing.JTabbedPane();
        examPane = new javax.swing.JPanel();
        btnPane2 = new javax.swing.JPanel();
        manageExamBtn = new javax.swing.JButton();
        marksBtn = new javax.swing.JButton();
        performanceBtn = new javax.swing.JButton();
        examDesktopPane = new javax.swing.JDesktopPane();
        paymentPane = new javax.swing.JPanel();
        btnPane3 = new javax.swing.JPanel();
        addPaymentBtn = new javax.swing.JButton();
        deletePaymentBtn = new javax.swing.JButton();
        detailLbl2 = new javax.swing.JLabel();
        paymentDesktopPane = new javax.swing.JDesktopPane();
        employeePane = new javax.swing.JPanel();
        btnPane4 = new javax.swing.JPanel();
        addEmployeeBtn = new javax.swing.JButton();
        updateEmployeeBtn = new javax.swing.JButton();
        deleteEmployeeBtn = new javax.swing.JButton();
        workDetailBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        employeeDesktopPane = new javax.swing.JDesktopPane();
        studentPane = new javax.swing.JPanel();
        btnPane1 = new javax.swing.JPanel();
        addStudentBtn = new javax.swing.JButton();
        searchStudentBtn = new javax.swing.JButton();
        updateStudentBtn = new javax.swing.JButton();
        deleteStudentBtn = new javax.swing.JButton();
        weeklyAttendanceBtn = new javax.swing.JButton();
        studentDesktopPane = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        homeBtn = new javax.swing.JButton();
        helpBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        refreshBtn = new javax.swing.JButton();
        usrNme = new javax.swing.JLabel();
        IDNum = new javax.swing.JLabel();
        userImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");
        setPreferredSize(new java.awt.Dimension(670, 433));

        mainTabPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        examPane.setToolTipText("Exam");

        manageExamBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/exam_images/add_Exam.png"))); // NOI18N
        manageExamBtn.setText("Manage");
        manageExamBtn.setIconTextGap(10);
        manageExamBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageExamBtnActionPerformed(evt);
            }
        });

        marksBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/exam_images/update_Exam.png"))); // NOI18N
        marksBtn.setText("Marks");
        marksBtn.setIconTextGap(15);
        marksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marksBtnActionPerformed(evt);
            }
        });

        performanceBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/exam_images/performance.png"))); // NOI18N
        performanceBtn.setText("Performance");
        performanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                performanceBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnPane2Layout = new javax.swing.GroupLayout(btnPane2);
        btnPane2.setLayout(btnPane2Layout);
        btnPane2Layout.setHorizontalGroup(
            btnPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageExamBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(marksBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnPane2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(performanceBtn)))
                .addContainerGap())
        );
        btnPane2Layout.setVerticalGroup(
            btnPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPane2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(manageExamBtn)
                .addGap(18, 18, 18)
                .addComponent(marksBtn)
                .addGap(18, 18, 18)
                .addComponent(performanceBtn)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        examDesktopPane.setOpaque(false);

        javax.swing.GroupLayout examDesktopPaneLayout = new javax.swing.GroupLayout(examDesktopPane);
        examDesktopPane.setLayout(examDesktopPaneLayout);
        examDesktopPaneLayout.setHorizontalGroup(
            examDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 988, Short.MAX_VALUE)
        );
        examDesktopPaneLayout.setVerticalGroup(
            examDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 854, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout examPaneLayout = new javax.swing.GroupLayout(examPane);
        examPane.setLayout(examPaneLayout);
        examPaneLayout.setHorizontalGroup(
            examPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(examPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(examDesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        examPaneLayout.setVerticalGroup(
            examPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(examPaneLayout.createSequentialGroup()
                .addComponent(btnPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(examDesktopPane)
        );

        mainTabPane.addTab("Exam", new javax.swing.ImageIcon(getClass().getResource("/resources/exam_images/exam.png")), examPane); // NOI18N

        paymentPane.setToolTipText("Payment");

        btnPane3.setToolTipText("Payment");

        addPaymentBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/payment_images/add_Payment.png"))); // NOI18N
        addPaymentBtn.setText("Add");
        addPaymentBtn.setIconTextGap(33);
        addPaymentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPaymentBtnActionPerformed(evt);
            }
        });

        deletePaymentBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/payment_images/delete_Payment.png"))); // NOI18N
        deletePaymentBtn.setText("Delete");
        deletePaymentBtn.setIconTextGap(23);
        deletePaymentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePaymentBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnPane3Layout = new javax.swing.GroupLayout(btnPane3);
        btnPane3.setLayout(btnPane3Layout);
        btnPane3Layout.setHorizontalGroup(
            btnPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addPaymentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deletePaymentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(detailLbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        btnPane3Layout.setVerticalGroup(
            btnPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addPaymentBtn)
                .addGap(18, 18, 18)
                .addComponent(deletePaymentBtn)
                .addGap(135, 135, 135)
                .addComponent(detailLbl2, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addContainerGap())
        );

        paymentDesktopPane.setOpaque(false);

        javax.swing.GroupLayout paymentDesktopPaneLayout = new javax.swing.GroupLayout(paymentDesktopPane);
        paymentDesktopPane.setLayout(paymentDesktopPaneLayout);
        paymentDesktopPaneLayout.setHorizontalGroup(
            paymentDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 834, Short.MAX_VALUE)
        );
        paymentDesktopPaneLayout.setVerticalGroup(
            paymentDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout paymentPaneLayout = new javax.swing.GroupLayout(paymentPane);
        paymentPane.setLayout(paymentPaneLayout);
        paymentPaneLayout.setHorizontalGroup(
            paymentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(paymentDesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        paymentPaneLayout.setVerticalGroup(
            paymentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPaneLayout.createSequentialGroup()
                .addGroup(paymentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paymentPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paymentPaneLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(paymentDesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(311, Short.MAX_VALUE))
        );

        mainTabPane.addTab("Payment", new javax.swing.ImageIcon(getClass().getResource("/resources/payment_images/payment.png")), paymentPane); // NOI18N

        employeePane.setToolTipText("Employee");

        addEmployeeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/employee_images/addEmpoloyee.png"))); // NOI18N
        addEmployeeBtn.setText("Add");
        addEmployeeBtn.setIconTextGap(33);
        addEmployeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeBtnActionPerformed(evt);
            }
        });

        updateEmployeeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/employee_images/updateEmpoloyee.png"))); // NOI18N
        updateEmployeeBtn.setText("Update");
        updateEmployeeBtn.setIconTextGap(20);
        updateEmployeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmployeeBtnActionPerformed(evt);
            }
        });

        deleteEmployeeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/employee_images/deleteEmpoloyee.png"))); // NOI18N
        deleteEmployeeBtn.setText("Delete");
        deleteEmployeeBtn.setIconTextGap(23);
        deleteEmployeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteEmployeeBtnActionPerformed(evt);
            }
        });

        workDetailBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/employee_images/employeeWorkDet.png"))); // NOI18N
        workDetailBtn.setText("Working Details");
        workDetailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workDetailBtnActionPerformed(evt);
            }
        });

        searchBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/employee_images/searchEmpoloyee.png"))); // NOI18N
        searchBtn.setText("Search");
        searchBtn.setIconTextGap(23);
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnPane4Layout = new javax.swing.GroupLayout(btnPane4);
        btnPane4.setLayout(btnPane4Layout);
        btnPane4Layout.setHorizontalGroup(
            btnPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addEmployeeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateEmployeeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteEmployeeBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(workDetailBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        btnPane4Layout.setVerticalGroup(
            btnPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addEmployeeBtn)
                .addGap(18, 18, 18)
                .addComponent(updateEmployeeBtn)
                .addGap(18, 18, 18)
                .addComponent(deleteEmployeeBtn)
                .addGap(18, 18, 18)
                .addComponent(searchBtn)
                .addGap(18, 18, 18)
                .addComponent(workDetailBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        employeeDesktopPane.setOpaque(false);

        javax.swing.GroupLayout employeeDesktopPaneLayout = new javax.swing.GroupLayout(employeeDesktopPane);
        employeeDesktopPane.setLayout(employeeDesktopPaneLayout);
        employeeDesktopPaneLayout.setHorizontalGroup(
            employeeDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 834, Short.MAX_VALUE)
        );
        employeeDesktopPaneLayout.setVerticalGroup(
            employeeDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout employeePaneLayout = new javax.swing.GroupLayout(employeePane);
        employeePane.setLayout(employeePaneLayout);
        employeePaneLayout.setHorizontalGroup(
            employeePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(employeeDesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        employeePaneLayout.setVerticalGroup(
            employeePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPane4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(employeePaneLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(employeeDesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(313, Short.MAX_VALUE))
        );

        mainTabPane.addTab("Employee", new javax.swing.ImageIcon(getClass().getResource("/resources/employee_images/employee.png")), employeePane); // NOI18N

        studentPane.setToolTipText("Student");

        addStudentBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/student_images/addStudent.png"))); // NOI18N
        addStudentBtn.setText("Add");
        addStudentBtn.setIconTextGap(33);
        addStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentBtnActionPerformed(evt);
            }
        });

        searchStudentBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/student_images/searchStudent.png"))); // NOI18N
        searchStudentBtn.setText("Search");
        searchStudentBtn.setIconTextGap(20);
        searchStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchStudentBtnActionPerformed(evt);
            }
        });

        updateStudentBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/student_images/updateStudent.png"))); // NOI18N
        updateStudentBtn.setText("Update");
        updateStudentBtn.setIconTextGap(20);
        updateStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateStudentBtnActionPerformed(evt);
            }
        });

        deleteStudentBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/student_images/deleteStudent.png"))); // NOI18N
        deleteStudentBtn.setText("Delete");
        deleteStudentBtn.setIconTextGap(23);
        deleteStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteStudentBtnActionPerformed(evt);
            }
        });

        weeklyAttendanceBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/student_images/viewAttendance.png"))); // NOI18N
        weeklyAttendanceBtn.setText("Attendance");
        weeklyAttendanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weeklyAttendanceBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnPane1Layout = new javax.swing.GroupLayout(btnPane1);
        btnPane1.setLayout(btnPane1Layout);
        btnPane1Layout.setHorizontalGroup(
            btnPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addStudentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchStudentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(updateStudentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deleteStudentBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(btnPane1Layout.createSequentialGroup()
                        .addComponent(weeklyAttendanceBtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        btnPane1Layout.setVerticalGroup(
            btnPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addStudentBtn)
                .addGap(18, 18, 18)
                .addComponent(searchStudentBtn)
                .addGap(18, 18, 18)
                .addComponent(updateStudentBtn)
                .addGap(18, 18, 18)
                .addComponent(deleteStudentBtn)
                .addGap(18, 18, 18)
                .addComponent(weeklyAttendanceBtn)
                .addContainerGap(219, Short.MAX_VALUE))
        );

        studentDesktopPane.setOpaque(false);

        javax.swing.GroupLayout studentDesktopPaneLayout = new javax.swing.GroupLayout(studentDesktopPane);
        studentDesktopPane.setLayout(studentDesktopPaneLayout);
        studentDesktopPaneLayout.setHorizontalGroup(
            studentDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 972, Short.MAX_VALUE)
        );
        studentDesktopPaneLayout.setVerticalGroup(
            studentDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout studentPaneLayout = new javax.swing.GroupLayout(studentPane);
        studentPane.setLayout(studentPaneLayout);
        studentPaneLayout.setHorizontalGroup(
            studentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentDesktopPane))
        );
        studentPaneLayout.setVerticalGroup(
            studentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentPaneLayout.createSequentialGroup()
                        .addComponent(btnPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(256, Short.MAX_VALUE))
                    .addComponent(studentDesktopPane, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        mainTabPane.addTab("Student", new javax.swing.ImageIcon(getClass().getResource("/resources/student_images/student.png")), studentPane); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabPane)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainTabPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other_images/strip.png"))); // NOI18N

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other_images/home.png"))); // NOI18N
        homeBtn.setToolTipText("Home");
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });

        helpBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other_images/help.png"))); // NOI18N
        helpBtn.setToolTipText("Help");
        helpBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpBtnActionPerformed(evt);
            }
        });

        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other_images/shut_down.png"))); // NOI18N
        logoutBtn.setToolTipText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        refreshBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/other_images/account settings.png"))); // NOI18N
        refreshBtn.setToolTipText("Account Settings");
        refreshBtn.setIconTextGap(6);
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        usrNme.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        usrNme.setBorder(javax.swing.BorderFactory.createTitledBorder("User Name"));

        IDNum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IDNum.setBorder(javax.swing.BorderFactory.createTitledBorder("Designation"));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(helpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usrNme, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(IDNum, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(refreshBtn)
                    .addComponent(logoutBtn)
                    .addComponent(helpBtn)
                    .addComponent(homeBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usrNme, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDNum, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        userImage.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        userImage.setMaximumSize(new java.awt.Dimension(128, 128));
        userImage.setPreferredSize(new java.awt.Dimension(130, 130));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(userImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(userImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(56, 56, 56))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1288, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getAccessibleContext().setAccessibleName("Sasip");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentBtnActionPerformed
        AddStudent addStudent = new AddStudent(new StudentDetailController());
        addStudent.setEmpID(username);
        addComponentTo(addStudent, studentDesktopPane);
    }//GEN-LAST:event_addStudentBtnActionPerformed

    private void searchStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchStudentBtnActionPerformed
        SearchStudent searchStudent = new SearchStudent(new StudentDetailController());
        addComponentTo(searchStudent, studentDesktopPane);
    }//GEN-LAST:event_searchStudentBtnActionPerformed

    private void deleteStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteStudentBtnActionPerformed
        DeleteStudent deleteStudent = new DeleteStudent(new StudentDetailController());
        addComponentTo(deleteStudent, studentDesktopPane);
    }//GEN-LAST:event_deleteStudentBtnActionPerformed

    private void updateStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateStudentBtnActionPerformed
        EditStudent editStudent = new EditStudent(new StudentDetailController());
        addComponentTo(editStudent, studentDesktopPane);
    }//GEN-LAST:event_updateStudentBtnActionPerformed

    private void manageExamBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageExamBtnActionPerformed
        Exams exams = new Exams();
        addComponentTo(exams, examDesktopPane);
    }//GEN-LAST:event_manageExamBtnActionPerformed

    private void weeklyAttendanceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weeklyAttendanceBtnActionPerformed
        AttendanceManagement attendance = new AttendanceManagement(new StudentDetailController(), new AttendanceController(), new BarcodeReader(),userID);
//        attendance.setCurrentEmployee(username);
        addComponentTo1(attendance, studentDesktopPane);
    }//GEN-LAST:event_weeklyAttendanceBtnActionPerformed

    private void addEmployeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeBtnActionPerformed
        AddEmployee addEmployee = new AddEmployee(new EmployeeController());
        addComponentTo(addEmployee, employeeDesktopPane);
    }//GEN-LAST:event_addEmployeeBtnActionPerformed

    private void updateEmployeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmployeeBtnActionPerformed
        EditEmployee editEmployee = new EditEmployee(new EmployeeController());
        addComponentTo(editEmployee, employeeDesktopPane);
    }//GEN-LAST:event_updateEmployeeBtnActionPerformed

    private void deleteEmployeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteEmployeeBtnActionPerformed
        DeleteEmployee deleteEmployeeForm = new DeleteEmployee(new EmployeeController());
        addComponentTo(deleteEmployeeForm, employeeDesktopPane);
    }//GEN-LAST:event_deleteEmployeeBtnActionPerformed

    private void workDetailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workDetailBtnActionPerformed
        ViewWorkingDetail viewWorkingDetail = new ViewWorkingDetail(new EmployeeController(), new WorkingDetailsController());
        addComponentTo(viewWorkingDetail, employeeDesktopPane);
    }//GEN-LAST:event_workDetailBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        int res = JOptionPane.showConfirmDialog(this, "Are you sure you want to logout?");
        if (res == 0) {
            this.setVisible(false);
            new LoginWindowInterface().setVisible(true);
        }
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        studentDesktopPane.removeAll();
        mainTabPane.setSelectedIndex(0);
        paymentDesktopPane.removeAll();
        examDesktopPane.removeAll();
        employeeDesktopPane.removeAll();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void helpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpBtnActionPerformed
        Help help = new Help(this, false);
        help.setLocation(900, 200);
        help.setVisible(true);
    }//GEN-LAST:event_helpBtnActionPerformed

    private void marksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marksBtnActionPerformed
        Marks marks = new Marks();
        addComponentTo(marks, examDesktopPane);
    }//GEN-LAST:event_marksBtnActionPerformed

    private void addPaymentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPaymentBtnActionPerformed
        AddPayment addPayment = new AddPayment(userID);
        addComponentTo(addPayment, paymentDesktopPane);
    }//GEN-LAST:event_addPaymentBtnActionPerformed

    private void deletePaymentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePaymentBtnActionPerformed
        DeletePayment deletePayment = new DeletePayment();
        addComponentTo(deletePayment, paymentDesktopPane);
    }//GEN-LAST:event_deletePaymentBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        SearchEmployee searchEmployee = new SearchEmployee(new EmployeeController());
        addComponentTo(searchEmployee, employeeDesktopPane);
    }//GEN-LAST:event_searchBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        AccountSettings accountSettings = new AccountSettings(this, true);
        accountSettings.setLocation(500, 250);
        accountSettings.setVisible(true);
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void performanceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_performanceBtnActionPerformed
        Peformance peformance = new Peformance();
        addComponentTo(peformance, examDesktopPane);
    }//GEN-LAST:event_performanceBtnActionPerformed
    
    private void setUser() {
        
    }
    
    public static String getUserName() {
        return username;
    }
    
    public void addComponentTo(JInternalFrame frame, JDesktopPane pane) {
        JInternalFrame frames[] = pane.getAllFrames();
        
        if (frames.length == 0) {
            ((javax.swing.plaf.basic.BasicInternalFrameUI) frame.getUI()).setNorthPane(null);
            pane.add(frame);
            pane.setLocation(250, 10);
            frame.setVisible(true);
        } else {
            pane.removeAll();
            ((javax.swing.plaf.basic.BasicInternalFrameUI) frame.getUI()).setNorthPane(null);
            pane.add(frame);
            pane.setLocation(250, 10);
            frame.setVisible(true);
        }
    }

    public void addComponentTo1(JInternalFrame frame, JDesktopPane pane) {
        JInternalFrame frames[] = pane.getAllFrames();
        frame.setBorder(null);
        pane.setMaximumSize(new Dimension(988, 854));
        pane.setMinimumSize(new Dimension(988, 854));
        pane.setPreferredSize(new Dimension(988, 854));
        
        if (frames.length == 0) {
            ((javax.swing.plaf.basic.BasicInternalFrameUI) frame.getUI()).setNorthPane(null);
      
            pane.add(frame);
            pane.setLocation(250, 10);
            frame.setVisible(true);
        } else {
            pane.removeAll();
            ((javax.swing.plaf.basic.BasicInternalFrameUI) frame.getUI()).setNorthPane(null);
            pane.add(frame);
            pane.setLocation(250, 10);
            frame.setVisible(true);
        }
    }
    
    public JButton getAddEmployeeBtn() {
        return addEmployeeBtn;
    }
    
    public JButton getManageExamBtn() {
        return manageExamBtn;
    }
    
    public JButton getAddPaymentBtn() {
        return addPaymentBtn;
    }
    
    public JButton getAddStudentBtn() {
        return addStudentBtn;
    }
    
    public JButton getDeleteEmployeeBtn() {
        return deleteEmployeeBtn;
    }
    
    public JButton getDeletePaymentBtn() {
        return deletePaymentBtn;
    }
    
    public JButton getDeleteStudentBtn() {
        return deleteStudentBtn;
    }
    
    public JButton getPerformanceBtn() {
        return performanceBtn;
    }
    
    public JButton getUpdateEmployeeBtn() {
        return updateEmployeeBtn;
    }
    
    public JButton getMarksBtn() {
        return marksBtn;
    }
    
    public JButton getUpdateStudentBtn() {
        return updateStudentBtn;
    }
    
    public JButton getWeeklyAttendanceBtn() {
        return weeklyAttendanceBtn;
    }
    
    public JButton getWorkDetailBtn() {
        return workDetailBtn;
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /*
//         * Set the Nimbus look and feel
//         */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /*
//         * If Nimbus (introduced in Java SE 6) is not available, stay with the
//         * default look and feel. For details see
//         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Windows".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /*
//         * Create and display the form
//         */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {                
//                MainGUI mainGUI = new MainGUI();
//                mainGUI.setExtendedState(JFrame.MAXIMIZED_BOTH);
//                mainGUI.setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDNum;
    private javax.swing.JButton addEmployeeBtn;
    private javax.swing.JButton addPaymentBtn;
    private javax.swing.JButton addStudentBtn;
    private javax.swing.JPanel btnPane1;
    private javax.swing.JPanel btnPane2;
    private javax.swing.JPanel btnPane3;
    private javax.swing.JPanel btnPane4;
    private javax.swing.JButton deleteEmployeeBtn;
    private javax.swing.JButton deletePaymentBtn;
    private javax.swing.JButton deleteStudentBtn;
    private javax.swing.JLabel detailLbl2;
    private javax.swing.JDesktopPane employeeDesktopPane;
    private javax.swing.JPanel employeePane;
    private javax.swing.JDesktopPane examDesktopPane;
    private javax.swing.JPanel examPane;
    private javax.swing.JButton helpBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTabbedPane mainTabPane;
    private javax.swing.JButton manageExamBtn;
    private javax.swing.JButton marksBtn;
    private javax.swing.JDesktopPane paymentDesktopPane;
    private javax.swing.JPanel paymentPane;
    private javax.swing.JButton performanceBtn;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton searchStudentBtn;
    private javax.swing.JDesktopPane studentDesktopPane;
    private javax.swing.JPanel studentPane;
    private javax.swing.JButton updateEmployeeBtn;
    private javax.swing.JButton updateStudentBtn;
    private javax.swing.JLabel userImage;
    private javax.swing.JLabel usrNme;
    private javax.swing.JButton weeklyAttendanceBtn;
    private javax.swing.JButton workDetailBtn;
    // End of variables declaration//GEN-END:variables
}
