/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.payment;

/**
 *
 * @author Yasanka Jayawardane
 */
public class DeletePayment extends javax.swing.JInternalFrame {

    /**
     * Creates new form DeletePayment
     */
    public DeletePayment() {
        initComponents();
        
        DeleteMonthPay deleteMonth = new DeleteMonthPay();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) deleteMonth.getUI()).setNorthPane(null);
        deleteMonth.setVisible(true);
        deleteMonthPay.add(deleteMonth);
        
        
        DeleteExamPay deleteExam = new DeleteExamPay();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) deleteExam.getUI()).setNorthPane(null);
        deleteExam.setVisible(true);
        deleteExamPay.add(deleteExam);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        deleteMonthPay = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        deleteExamPay = new javax.swing.JDesktopPane();

        setBorder(null);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        deleteMonthPay.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        deleteMonthPay.setOpaque(false);

        javax.swing.GroupLayout deleteMonthPayLayout = new javax.swing.GroupLayout(deleteMonthPay);
        deleteMonthPay.setLayout(deleteMonthPayLayout);
        deleteMonthPayLayout.setHorizontalGroup(
            deleteMonthPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );
        deleteMonthPayLayout.setVerticalGroup(
            deleteMonthPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deleteMonthPay)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deleteMonthPay)
        );

        jTabbedPane1.addTab("Monthly Payment", jPanel1);

        deleteExamPay.setOpaque(false);

        javax.swing.GroupLayout deleteExamPayLayout = new javax.swing.GroupLayout(deleteExamPay);
        deleteExamPay.setLayout(deleteExamPayLayout);
        deleteExamPayLayout.setHorizontalGroup(
            deleteExamPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 645, Short.MAX_VALUE)
        );
        deleteExamPayLayout.setVerticalGroup(
            deleteExamPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 399, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deleteExamPay)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(deleteExamPay)
        );

        jTabbedPane1.addTab("Exam Payment", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane deleteExamPay;
    private javax.swing.JDesktopPane deleteMonthPay;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
