/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.payment;

import controller.payment.PaymentController;
import controller.student.StudentDetailController;
import datalayer.payment.MonthlyPaymentDA;
import java.awt.Component;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.student.Student;
import utilities.ComboBoxUtility;

/**
 *
 * @author Yasanka Jayawardane
 */
public class DeleteMonthPay extends javax.swing.JInternalFrame {
    
    /**
     * Creates new form DeleteMonthPay
     */
    DefaultListModel<String> listModel;
    ArrayList <String> listPay;
    Student payingStudent;
    PaymentController payControl;
    StudentDetailController stdController; 
    public DeleteMonthPay() {
        listModel = new DefaultListModel<>();
        listPay = new ArrayList<>();
        payControl = new PaymentController();
        stdController =  new StudentDetailController();
        initComponents();
        myInitComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        studentIDCmbx = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        deletePaymentTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        studentNameTxt = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        paymentList = new javax.swing.JList();
        clearBtn = new javax.swing.JButton();

        setBorder(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Delete Month Payment", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Student ID :");

        studentIDCmbx.setEditable(true);
        studentIDCmbx.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        studentIDCmbx.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                studentIDCmbxItemStateChanged(evt);
            }
        });
        studentIDCmbx.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                studentIDCmbxCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Student Name :");

        deletePaymentTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Deletable Payment :");

        studentNameTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        studentNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentNameTxtActionPerformed(evt);
            }
        });

        deleteBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.setEnabled(false);
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        paymentList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        paymentList.setModel(listModel);
        paymentList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        paymentList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                paymentListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(paymentList);

        jScrollPane2.setViewportView(jScrollPane1);

        clearBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(studentIDCmbx, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(studentNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                                    .addComponent(deletePaymentTxt))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(studentIDCmbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(studentNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(deletePaymentTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
     private void myInitComponents(){
        try {
            ComboBoxUtility.setComboItem(studentIDCmbx, "Select studentID from student order by 1");
            JTextField txt1 = (JTextField) studentIDCmbx.getEditor().getEditorComponent();
            
            new ComboBoxUtility().setSearchableCombo(studentIDCmbx, txt1, "No such student");
         
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Database Error!"); 
        }
    }
    private void studentNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentNameTxtActionPerformed

    private void paymentListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_paymentListValueChanged
        // TODO add your handling code here:
        deletePaymentTxt.setText((String)paymentList.getSelectedValue());
        deleteBtn.setEnabled(true);
    }//GEN-LAST:event_paymentListValueChanged

    private void studentIDCmbxCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_studentIDCmbxCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIDCmbxCaretPositionChanged

    private void studentIDCmbxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_studentIDCmbxItemStateChanged
        // TODO add your handling code here:
        
        try {
            listModel.removeAllElements();
            listPay.removeAll(listPay);
            payingStudent = stdController.searchStudentByID((String)studentIDCmbx.getSelectedItem());
            studentNameTxt.setText(payingStudent.getFirstName()+" "+payingStudent.getLastName());
            ResultSet rst = payControl.getMonthlyPaymentHistory((String)studentIDCmbx.getSelectedItem());
            while(rst.next()){
                listModel.addElement(rst.getString(2)+"  ["+rst.getString(3)+"]  ["+rst.getString(4 )+"]");
                listPay.add(rst.getString(1));
            } 
           
        } 
        catch (NullPointerException ex) {
            //Logger.getLogger(DeleteMonthPay.class.getName()).log(Level.SEVERE, null, ex);
        }
            catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(DeleteMonthPay.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_studentIDCmbxItemStateChanged

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int index = paymentList.getSelectedIndex();
        try {
            String stuID = payingStudent.getStudentID();
            String payID = listPay.get(index);
            if(!stuID.equals("")||!payID.equals("")){
                int x = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete this Payment :\n"+stuID+"\n"+payID);
                
                if(x == 0 ){
                   int y =payControl.deleteOneMonthPaymentRecord(stuID, payID);
                   if(y == 1){
                       JOptionPane.showMessageDialog(this, "Successfully Deleted");
                       clearBtnActionPerformed(evt);
                   }
                   
                   else{
                       JOptionPane.showMessageDialog(this, "Delete was not Success!");
                   }
                  
                }
                
            }
            
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(DeleteMonthPay.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        deleteBtn.setEnabled(false);
        studentNameTxt.setText("");
        deletePaymentTxt.setText("");
        listModel.removeAllElements();
    }//GEN-LAST:event_clearBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField deletePaymentTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList paymentList;
    private javax.swing.JComboBox studentIDCmbx;
    private javax.swing.JTextField studentNameTxt;
    // End of variables declaration//GEN-END:variables
}
