/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view.payment;

import controller.payment.PaymentController;
import controller.student.StudentDetailController;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import utilities.ComboBoxUtility;
import model.student.Student;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.payment.*;
import utilities.AddRecordException;

/**
 *
 * @author Yasanka Jayawardane
 */
public class MonthPayment extends javax.swing.JInternalFrame {
    
    private Student payingStudent;
    private model.payment.MonthlyFeePayment monthPay;
    
    private String employeeID;
    private PaymentController payController ;
    StudentDetailController stdController; 
    private boolean isValid ;
    private Double payabaleAmount;
    private Double receivedAmount;
    private Double balanceAmount ;
    private Date date;
    private ArrayList <String> classID;
    private PaymentSheet<MonthlyFeePayment> MonthPaySheet ;
    private String nextMonth;
    private String classIDStr;
    
    /**
     * Creates new form FeePayments
     */
    public MonthPayment(String userID) {
    employeeID = userID;
    payController = new PaymentController();
    stdController = new StudentDetailController();
    isValid = false;
    payabaleAmount = 0.00;
    receivedAmount = 0.00;
    balanceAmount = 0.00;
    
    nextMonth = "";
    classIDStr = "";
    
    date = new Date();
    classID = new ArrayList<>();
    MonthPaySheet =  new PaymentSheet<>();
    
        initComponents();
        myInitComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
            
    
    private void myInitComponents(){  
        SimpleDateFormat sdf = new SimpleDateFormat("YYYY - MMMM - dd");
        paymentDateTxt.setText(sdf.format(date));
        
        try {
            ComboBoxUtility.setComboItem(studentIDCmbx, "Select studentID from student order by 1");
            JTextField txt1 = (JTextField) studentIDCmbx.getEditor().getEditorComponent();
            new ComboBoxUtility().setSearchableCombo(studentIDCmbx, txt1, "No such student");
         
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Database Error!"); 
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cashAmountTxt = new javax.swing.JTextField();
        balanceTxt = new javax.swing.JTextField();
        cashReceivedTxt = new javax.swing.JTextField();
        receivedDetailLbl = new javax.swing.JLabel();
        cashRdbtn = new javax.swing.JRadioButton();
        freeCardRdbtn = new javax.swing.JRadioButton();
        saveBtn = new javax.swing.JButton();
        updDbBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        classTypeCmbx = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        studentIDCmbx = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        studentNameTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        paymentDateTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        payMonthtxt = new javax.swing.JTextField();

        setBorder(null);
        setPreferredSize(new java.awt.Dimension(710, 510));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Monthly Payments", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cash Payment", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Amount :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Payment Received :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Balance :");

        cashAmountTxt.setEditable(false);
        cashAmountTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        balanceTxt.setEditable(false);
        balanceTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cashReceivedTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cashReceivedTxt.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                cashReceivedTxtCaretUpdate(evt);
            }
        });

        receivedDetailLbl.setForeground(new java.awt.Color(255, 0, 0));

        cashRdbtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cashRdbtn.setText("Cash");
        cashRdbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashRdbtnActionPerformed(evt);
            }
        });

        freeCardRdbtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        freeCardRdbtn.setText("Free Card");
        freeCardRdbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                freeCardRdbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(receivedDetailLbl)
                                .addGap(33, 33, 33))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cashReceivedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cashAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(balanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(68, Short.MAX_VALUE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(cashRdbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(freeCardRdbtn)
                        .addGap(65, 65, 65))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashRdbtn)
                    .addComponent(freeCardRdbtn))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(receivedDetailLbl)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cashAmountTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cashReceivedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(balanceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addContainerGap(22, Short.MAX_VALUE))))
        );

        saveBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        updDbBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        updDbBtn.setText("Update Data Base");
        updDbBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updDbBtnActionPerformed(evt);
            }
        });

        clearBtn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        classTypeCmbx.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        classTypeCmbx.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                classTypeCmbxItemStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Class Type :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Student ID :");

        studentIDCmbx.setEditable(true);
        studentIDCmbx.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        studentIDCmbx.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                studentIDCmbxItemStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Student Name :");

        studentNameTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Payment Date :");

        paymentDateTxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        paymentDateTxt.setEnabled(false);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("Paying Month:");

        payMonthtxt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classTypeCmbx, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentIDCmbx, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(paymentDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(jLabel12)
                        .addGap(32, 32, 32)
                        .addComponent(payMonthtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(studentIDCmbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(studentNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(classTypeCmbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentDateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12)
                    .addComponent(payMonthtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updDbBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updDbBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cashRdbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashRdbtnActionPerformed
        // TODO add your handling code here:\
        
        payabaleAmount = 1000.0;
        cashAmountTxt.setText(Double.toString( payabaleAmount));
        freeCardRdbtn.setSelected(false);
        isValid = true;
    }//GEN-LAST:event_cashRdbtnActionPerformed

    private void freeCardRdbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_freeCardRdbtnActionPerformed
        // TODO add your handling code here:
        payabaleAmount = 0.0;
        cashAmountTxt.setText(Double.toString( payabaleAmount));
        cashRdbtn.setSelected(false);
        isValid = true;
    }//GEN-LAST:event_freeCardRdbtnActionPerformed

    private void cashReceivedTxtCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_cashReceivedTxtCaretUpdate
        // TODO add your handling code here:
        String tel = cashReceivedTxt.getText();
        boolean isLetter = false;
        for (int i = 0; i < tel.length(); i++) {
            if (!Character.isDigit(tel.charAt(i))) {
                isLetter = true;
                break;
            }
        }
        if (isLetter) {
            receivedDetailLbl.setText("Invalid amount");
        } else {
            receivedDetailLbl.setText("");
        }
        
        try{
            receivedAmount = Double.parseDouble(cashReceivedTxt.getText());//(cashReceivedTxt.getText());
        }
        
        catch(NumberFormatException ex){
            receivedAmount = 0.00;
        }
        balanceAmount = receivedAmount - payabaleAmount;
        balanceTxt.setText(Double.toString(balanceAmount));
        
    }//GEN-LAST:event_cashReceivedTxtCaretUpdate

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        if(isValid){
            
                try {
                    monthPay = new model.payment.MonthlyFeePayment(payingStudent.getStudentID(), classIDStr, nextMonth, employeeID, payController.nextPaymentID(), 1000.0, date);
                    MonthPaySheet.addPayments(monthPay);
                } catch (    ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(MonthPayment.class.getName()).log(Level.SEVERE, null, ex);
                }
        }
        else{
           JOptionPane.showMessageDialog(this, "Please check the data you entered");
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void studentIDCmbxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_studentIDCmbxItemStateChanged
        try {
            
            payingStudent = stdController.searchStudentByID((String)studentIDCmbx.getSelectedItem());
            studentNameTxt.setText(payingStudent.getFirstName()+" "+payingStudent.getLastName());
            
            ResultSet rst = payController.getClassDetails(payingStudent.getStudentID());
            String index = "";
            classTypeCmbx.removeAllItems();
            classID.removeAll(classID);
            classTypeCmbx.addItem("");
            while(rst.next()){
                index = rst.getString(2)+" "+rst.getString(3);
                classTypeCmbx.addItem(index);
                classID.add(rst.getString(1));
            }
            
        } 
        
        catch(NullPointerException e){
        
        }
            catch (ClassNotFoundException ex) {
            Logger.getLogger(MonthPayment.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MonthPayment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_studentIDCmbxItemStateChanged

    private void classTypeCmbxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_classTypeCmbxItemStateChanged
        // TODO add your handling code here:
        int selectedIndex = classTypeCmbx.getSelectedIndex()-1;
        if(selectedIndex>=0 && !classID.isEmpty()){
            try {
                classIDStr = classID.get(selectedIndex);
                nextMonth =payController.nextPaymentMonth(payingStudent.getStudentID(),classIDStr);
             } catch (    ClassNotFoundException | SQLException ex) {
                Logger.getLogger(MonthPayment.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        payMonthtxt.setText(nextMonth);
        
    }//GEN-LAST:event_classTypeCmbxItemStateChanged

    private void updDbBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updDbBtnActionPerformed
        try {
            // TODO add your handling code here:
            boolean state = false;
            
            state = payController.addMonthPayments(MonthPaySheet);
            
            if(state){
                JOptionPane.showMessageDialog(null,"Succesfull","Datalink", JOptionPane.INFORMATION_MESSAGE);
                MonthPaySheet.clearSheet();
            }
            else{
                JOptionPane.showMessageDialog(null,"Unsuccesfull","Datalink", JOptionPane.INFORMATION_MESSAGE);
            }
                    } catch (SQLException ex) {
            Logger.getLogger(MonthPayment.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MonthPayment.class.getName()).log(Level.SEVERE, null, ex);
        } catch (AddRecordException ex) {
            Logger.getLogger(MonthPayment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updDbBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        studentNameTxt.setText("");
        paymentDateTxt.setText("");
        payMonthtxt.setText("");
        balanceTxt.setText("");
        cashAmountTxt.setText("");
        cashReceivedTxt.setText("");
        
                
    }//GEN-LAST:event_clearBtnActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField balanceTxt;
    private javax.swing.JTextField cashAmountTxt;
    private javax.swing.JRadioButton cashRdbtn;
    private javax.swing.JTextField cashReceivedTxt;
    private javax.swing.JComboBox classTypeCmbx;
    private javax.swing.JButton clearBtn;
    private javax.swing.JRadioButton freeCardRdbtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField payMonthtxt;
    private javax.swing.JTextField paymentDateTxt;
    private javax.swing.JLabel receivedDetailLbl;
    private javax.swing.JButton saveBtn;
    private javax.swing.JComboBox studentIDCmbx;
    private javax.swing.JTextField studentNameTxt;
    private javax.swing.JButton updDbBtn;
    // End of variables declaration//GEN-END:variables
}
